// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaSa72E00BPHXI41mpekQV1b-3Y2fD-F4',
    appId: '1:244970645498:web:1a5d6db0b6d3e32fcb6643',
    messagingSenderId: '244970645498',
    projectId: 'taxi-b2f06',
    authDomain: 'taxi-b2f06.firebaseapp.com',
    storageBucket: 'taxi-b2f06.firebasestorage.app',
    measurementId: 'G-MJKZXLN8LW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmdpoPfyRGIGLd3-OQqp7vsSrux7q3Nt0',
    appId: '1:244970645498:android:e161250d99ebd3bacb6643',
    messagingSenderId: '244970645498',
    projectId: 'taxi-b2f06',
    storageBucket: 'taxi-b2f06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv8uvoPX03H35W2CKs3tqplbHdIF-zVaQ',
    appId: '1:244970645498:ios:3daf04a7addcf6c1cb6643',
    messagingSenderId: '244970645498',
    projectId: 'taxi-b2f06',
    storageBucket: 'taxi-b2f06.firebasestorage.app',
    iosBundleId: 'com.example.cabApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv8uvoPX03H35W2CKs3tqplbHdIF-zVaQ',
    appId: '1:244970645498:ios:3daf04a7addcf6c1cb6643',
    messagingSenderId: '244970645498',
    projectId: 'taxi-b2f06',
    storageBucket: 'taxi-b2f06.firebasestorage.app',
    iosBundleId: 'com.example.cabApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaSa72E00BPHXI41mpekQV1b-3Y2fD-F4',
    appId: '1:244970645498:web:c30630c646cd2e5bcb6643',
    messagingSenderId: '244970645498',
    projectId: 'taxi-b2f06',
    authDomain: 'taxi-b2f06.firebaseapp.com',
    storageBucket: 'taxi-b2f06.firebasestorage.app',
    measurementId: 'G-NZXWL3PERT',
  );
}
